name: Utility - Remake All Index Pages

on:
  workflow_dispatch:

jobs:
  remake-all-indexes:
    runs-on: ubuntu-latest
    name: Remake File Index Pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Index Files
        run: |
          header_html="$(cat template_header.html)"
          footer_html="$(cat template_footer.html)"

          ## MAKE HOME TABLE INCLUDING FILES AND FOLDERS ##
          echo "Working on: home"
          table_html=""
          table_html+="<table class=\"table table-striped table-bordered table-hover\">"
          table_html+="<thead class=\"table-dark\"><tr><th>Name</th><th>Type</th><th>Last Modified</th></tr></thead>"
          table_html+=$'\n'

          # Loop through all items (files and directories) in the top-level directory
          for item in $(find . -mindepth 1 -maxdepth 1 ! -name ".*" | sort); do
            name=$(basename "$item")
            if [ -d "$item" ]; then
              type="Folder"
              link="$name/"
            else
              type="File"
              link="$name"
            fi
            # Get the last modified date
            modified=$(git log -1 --format=%cd --date=format:'%d %b %Y %I:%M %p' -- "$item" 2>/dev/null || date -r "$item" '+%d %b %Y %I:%M %p')
            # Create a table row with the item information
            table_html+="<tr><td><a class=\"file-link\" href=\"$link\">$name</a></td><td>$type</td><td>$modified</td></tr>"
            table_html+=$'\n'
          done
          table_html+="</table>"

          # Assemble and save HTML
          home_html="$header_html$table_html$footer_html"
          echo "$home_html" > "./index.html"

          ## RECURSIVELY GENERATE TABLES FOR ALL DIRECTORIES ##
          generate_table_for_directory() {
            local dir_path="$1"
            echo "Working on: $dir_path"
            local table_html=""
            table_html+="<table class=\"table table-striped table-bordered table-hover\">"
            table_html+="<thead class=\"table-dark\"><tr><th>Name</th><th>Type</th><th>Last Modified</th></tr></thead>"
            table_html+=$'\n'

            # Iterate through all items in the current directory
            for item in "$dir_path"/*; do
              [ -e "$item" ] || continue  # Skip if no items exist
              local name=$(basename "$item")
              if [ -d "$item" ]; then
                type="Folder"
                link="$name/"
                # Recursively process subdirectories
                generate_table_for_directory "$item"
              else
                type="File"
                link="$name"
              fi
              local modified=$(git log -1 --format=%cd --date=format:'%d %b %Y %I:%M %p' -- "$item" 2>/dev/null || date -r "$item" '+%d %b %Y %I:%M %p')
              table_html+="<tr><td><a class=\"file-link\" href=\"$link\">$name</a></td><td>$type</td><td>$modified</td></tr>"
              table_html+=$'\n'
            done
            table_html+="</table>"
            # Add parent directory link
            table_html+='<p><a href="../">Parent directory</a></p>'

            # Assemble and save HTML
            local full_html="$header_html$table_html$footer_html"
            echo "$full_html" > "$dir_path/index.html"
          }

          # Call the recursive function for top-level directories
          for type_dir in $(find . -mindepth 1 -maxdepth 1 -type d ! -name ".*"); do
            generate_table_for_directory "$type_dir"
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update file index pages'
          file_pattern: '**/index.html'
